apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  replicas: 2  # Number of replicas (you can adjust this based on load requirements)
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-container
        image: wanendeya/flask-app:latest 
        ports:
        - containerPort: 8080  # Port that the Flask application is exposing in Dockerfile
