name: CI/CD Pipeline

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and Push Docker image
        run: |
          docker build -t wanendeya/flask-app:latest .
          docker push wanendeya/flask-app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to Kind Kubernetes Cluster
        run: |
          kind create cluster
          kubectl apply -f deployment.yaml
          kubectl apply -f services.yaml
