name: CI/CD Pipeline

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Docker image
        run: |
          docker build -t "${{ secrets.DOCKER_USERNAME }}"/flask-app:latest .
          docker push "${{ secrets.DOCKER_USERNAME }}"/flask-app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to Kind Kubernetes Cluster
      working-directory: ./
      run: |
        kind create cluster
        kubectl apply -f deployment.yaml
        kubectl apply -f services.yaml


  